version: '3'

services:
  scheduler:
    build: .
    env_file: .env
    command: python -m bot.main --mode scheduler
    volumes:
      - ./:/app
    restart: unless-stopped

  websocket:
    build: .
    env_file: .env
    command: python -m bot.main --mode websocket
    volumes:
      - ./:/app
    restart: unless-stopped

